import type { editor } from "monaco-editor";

export const COMPANION_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: false,
  rules: [
    { token: "", foreground: "EDEDEE", background: "141416" },
    { token: "comment", foreground: "6E6E76", fontStyle: "italic" },
    { token: "comment.line", foreground: "6E6E76", fontStyle: "italic" },
    { token: "comment.block", foreground: "6E6E76", fontStyle: "italic" },
    { token: "string", foreground: "A5D6A7" },
    { token: "string.escape", foreground: "80CBC4" },
    { token: "constant.numeric", foreground: "FFB86C" },
    { token: "constant.language", foreground: "FF6B35" },
    { token: "constant", foreground: "FFB86C" },
    { token: "keyword", foreground: "FF6B35" },
    { token: "keyword.control", foreground: "FF6B35" },
    { token: "keyword.operator", foreground: "A1A1A6" },
    { token: "storage", foreground: "FF6B35" },
    { token: "storage.type", foreground: "FF6B35" },
    { token: "entity.name.function", foreground: "82AAFF" },
    { token: "entity.name.type", foreground: "FFCB6B" },
    { token: "entity.name.class", foreground: "FFCB6B" },
    { token: "entity.other.attribute-name", foreground: "82AAFF" },
    { token: "variable", foreground: "EDEDEE" },
    { token: "variable.language", foreground: "FF6B35" },
    { token: "variable.parameter", foreground: "C3E88D" },
    { token: "support.function", foreground: "82AAFF" },
    { token: "support.class", foreground: "FFCB6B" },
    { token: "support.type", foreground: "FFCB6B" },
    { token: "support.constant", foreground: "FFB86C" },
    { token: "invalid", foreground: "F87171" },
    { token: "tag", foreground: "F07178" },
    { token: "tag.attribute.name", foreground: "C3E88D" },
    { token: "operator", foreground: "A1A1A6" },
    { token: "delimiter", foreground: "A1A1A6" },
    { token: "punctuation", foreground: "A1A1A6" },
    { token: "type", foreground: "FFCB6B" },
    { token: "number", foreground: "FFB86C" },
    { token: "regexp", foreground: "80CBC4" },
  ],
  colors: {
    "editor.background": "#141416",
    "editor.foreground": "#EDEDEE",
    "editor.lineHighlightBackground": "#1A1A1D",
    "editor.lineHighlightBorder": "#1F1F23",
    "editor.selectionBackground": "#FF6B3530",
    "editor.selectionHighlightBackground": "#FF6B351A",
    "editor.findMatchBackground": "#FF6B3540",
    "editor.findMatchHighlightBackground": "#FF6B3520",
    "editor.wordHighlightBackground": "#1F1F23",
    "editorLineNumber.foreground": "#3A3A40",
    "editorLineNumber.activeForeground": "#6E6E76",
    "editorCursor.foreground": "#FF6B35",
    "editorWhitespace.foreground": "#27272B",
    "editorIndentGuide.background1": "#1F1F23",
    "editorIndentGuide.activeBackground1": "#27272B",
    "editorBracketMatch.background": "#FF6B3520",
    "editorBracketMatch.border": "#FF6B3560",
    "editorGutter.background": "#141416",
    "editorWidget.background": "#1A1A1D",
    "editorWidget.border": "#27272B",
    "editorSuggestWidget.background": "#1A1A1D",
    "editorSuggestWidget.border": "#27272B",
    "editorSuggestWidget.selectedBackground": "#FF6B3520",
    "editorHoverWidget.background": "#1A1A1D",
    "editorHoverWidget.border": "#27272B",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#3A3A4060",
    "scrollbarSlider.hoverBackground": "#3A3A4090",
    "scrollbarSlider.activeBackground": "#3A3A40",
    "minimap.background": "#0F0F10",
    "input.background": "#1A1A1D",
    "input.border": "#27272B",
    "input.foreground": "#EDEDEE",
  },
};

export const COMPANION_LIGHT_THEME: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: false,
  rules: [
    { token: "", foreground: "18181B", background: "FFFFFF" },
    { token: "comment", foreground: "71717A", fontStyle: "italic" },
    { token: "string", foreground: "166534" },
    { token: "constant.numeric", foreground: "D97706" },
    { token: "keyword", foreground: "E55A2B" },
    { token: "storage", foreground: "E55A2B" },
    { token: "entity.name.function", foreground: "2563EB" },
    { token: "entity.name.type", foreground: "7C3AED" },
    { token: "variable", foreground: "18181B" },
    { token: "type", foreground: "7C3AED" },
    { token: "number", foreground: "D97706" },
    { token: "operator", foreground: "52525B" },
  ],
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#18181B",
    "editor.lineHighlightBackground": "#F4F4F5",
    "editorLineNumber.foreground": "#D4D4D8",
    "editorLineNumber.activeForeground": "#A1A1AA",
    "editorCursor.foreground": "#E55A2B",
    "editorGutter.background": "#FFFFFF",
  },
};
